FORMAT: X-1A

# Almad hook testing. now. xoxo. 

Oh well. Tested on github animals. 

# Some group

## Retrieve SubResource [/Resource%28{id}%29/SubResource]

### Retrieve it [GET]

+ Parameters

    + id = `20` (number) ... ID of the resource

+ Response 200 (text/plain)

    ```
    SubResource response xoxo
    ```


## Retrieve Resource [/Resource%28{id}%29]


### Retrieve it [GET]

+ Request OMG
    + Headers

        ```
        Accept: text/html
        ```

+ Response 200 (text/plain)

    ```
    Resource response
    ```

