FORMAT: X-1A
HOST: http://example.com/

# Almad hook testing: creating conflicts for fun!

Oh well. Tested on github animals. Again. And Again. 

# Some group testingg

## Retrieve SubResource [/Resource%28{id}%29/SubResource]

### Retrieve it [GET]

+ Parameters

    + id = `20` (number) ... ID of the resource

+ Response 200 (text/plain)

    ```
    SubResource response xoxo
    ```


## Retrieve Resource [/Resource%28{id}%29]


### Retrieve it [GET]

+ Request OMG
    + Headers

        ```
        Accept: text/html
        ```

+ Response 200 (text/plain)

    ```
    Resource response
    ```

